//! Reproducible license texts and attribution for the two Linux image targets.

use crate::{Result, load::file_sha256, runtime};
use serde::Deserialize;
use std::{
    collections::BTreeMap,
    fmt::Write,
    fs,
    path::{Path, PathBuf},
};
use tokio::process::Command;

const ABOUT_VERSION: &str = "cargo-about 0.9.2";
const OUTPUT: &str = "THIRD_PARTY_NOTICES.txt";

#[derive(clap::Args)]
pub struct Args {
    /// Fail if the checked-in notices differ from the locked dependencies.
    #[arg(long)]
    pub check: bool,
}

#[derive(Deserialize)]
struct Graph {
    crates: Vec<CrateLicense>,
}

#[derive(Deserialize)]
struct CrateLicense {
    package: Package,
}

#[derive(Deserialize)]
struct Package {
    name: String,
    version: String,
    license: Option<String>,
    source: Option<String>,
    manifest_path: PathBuf,
}

#[derive(Deserialize)]
struct NativeNotices {
    name: String,
    version: String,
    output: PathBuf,
}

pub async fn run(args: Args) -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .ok_or("workspace root missing")?;
    let version = runtime::output(Command::new("cargo-about").arg("--version"), 10).await?;
    if !version.status.success() || String::from_utf8(version.stdout)?.trim() != ABOUT_VERSION {
        return Err("install cargo-about 0.9.2 with: cargo install cargo-about --version 0.9.2 --locked --features cli".into());
    }

    // cargo-about resolves the target graph and rejects unaccepted license
    // expressions. Harvest the actual files too: SPDX text alone loses NOTICE
    // attribution and licenses nested inside bundled native dependencies.
    let generated = runtime::output(
        Command::new("cargo-about").current_dir(root).args([
            "generate",
            "--locked",
            "--offline",
            "--fail",
            "--format",
            "json",
            "--config",
            "licenses/about.toml",
            "--manifest-path",
            "Cargo.toml",
        ]),
        120,
    )
    .await?;
    if !generated.status.success() {
        return Err(format!(
            "license resolution failed: {}",
            String::from_utf8_lossy(&generated.stderr)
        )
        .into());
    }

    let graph: Graph = serde_json::from_slice(&generated.stdout)?;
    let native: Vec<NativeNotices> =
        serde_json::from_slice(&fs::read(root.join("licenses/native.json"))?)?;
    let text = render(root, graph, &native)?;
    let destination = root.join(OUTPUT);

    if args.check {
        if fs::read_to_string(&destination)? != text {
            return Err(
                "third-party notices are stale; run cargo xtask notices and review the changes"
                    .into(),
            );
        }
    } else {
        fs::write(destination, text)?;
    }

    crate::emit_json(&serde_json::json!({"notices": OUTPUT, "checked": args.check}))
}

fn render(root: &Path, graph: Graph, native: &[NativeNotices]) -> Result<String> {
    let mut packages: Vec<_> = graph
        .crates
        .into_iter()
        .map(|item| item.package)
        .filter(|package| package.source.is_some())
        .collect();
    packages.sort_by(|left, right| (&left.name, &left.version).cmp(&(&right.name, &right.version)));

    for bundle in native {
        if !packages
            .iter()
            .any(|package| package.name == bundle.name && package.version == bundle.version)
        {
            return Err(format!(
                "review native license sources for {} {}; dependency version changed",
                bundle.name, bundle.version
            )
            .into());
        }
    }

    let mut output = format!(
        "Logbrook third-party notices\n\nGenerated by cargo xtask notices with {ABOUT_VERSION}.\nCargo.lock SHA-256: {}\n\n\
         Covers the Linux amd64 and arm64 application dependency graph.\n\
         Original license texts and attribution are reproduced below, including\n\
         alternative licenses and notices for bundled native source components.\n\
         These notices do not change Logbrook's MIT license or the terms of its\n\
         dependencies. Operating-system notices remain in the container base image.\n\n\
         Components (declared license expressions):\n",
        file_sha256(&root.join("Cargo.lock"))?
    );
    let mut texts: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for package in packages {
        writeln!(
            output,
            "- {} {}: {}",
            package.name,
            package.version,
            package
                .license
                .as_deref()
                .ok_or("dependency license expression missing")?
        )?;
        let directory = package
            .manifest_path
            .parent()
            .ok_or("crate directory missing")?;
        let mut files = Vec::new();
        collect_files(directory, &mut files)?;
        files.sort();
        let supplement = native.iter().find(|bundle| bundle.name == package.name);
        if files.is_empty() && supplement.is_none() {
            return Err(format!(
                "no license files for {} {}; add reviewed source notices",
                package.name, package.version
            )
            .into());
        }

        for file in files {
            let label = format!(
                "{} {} / {}",
                package.name,
                package.version,
                file.strip_prefix(directory)?.display()
            );
            texts.entry(read_notice(&file)?).or_default().push(label);
        }
        if let Some(bundle) = supplement {
            texts
                .entry(read_notice(&root.join(&bundle.output))?)
                .or_default()
                .push(format!(
                    "{} {} / upstream source notices",
                    package.name, package.version
                ));
        }
    }

    // Identical license files are shared, while distinct copyright statements
    // keep their own text. Neither registry paths nor timestamps enter output.
    for (text, mut components) in texts {
        components.sort();
        writeln!(
            output,
            "\n{}\n\n{}\n\n{text}",
            "=".repeat(78),
            components.join("\n")
        )?;
    }
    Ok(output)
}

fn read_notice(path: &Path) -> Result<String> {
    let text = fs::read_to_string(path)?.replace("\r\n", "\n");
    if text.trim().is_empty() {
        return Err(format!("empty license notice: {}", path.display()).into());
    }
    Ok(text.trim_end().to_owned())
}

fn collect_files(directory: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let kind = entry.file_type()?;
        if kind.is_dir() {
            collect_files(&entry.path(), files)?;
        } else if kind.is_file() {
            let name = entry.file_name().to_string_lossy().to_ascii_lowercase();
            let stem = name.split(['.', '-', '_']).next().unwrap_or("");
            if matches!(
                stem,
                "license" | "licence" | "notice" | "copying" | "copyright"
            ) {
                files.push(entry.path());
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_nested_notices_and_distinct_attribution_without_host_paths() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("Cargo.lock"), "fixture lockfile").unwrap();
        let directory = root.path().join("crate");
        fs::create_dir_all(directory.join("vendor")).unwrap();
        fs::write(
            directory.join("LICENSE"),
            "Copyright Alice\r\nMIT terms\r\n",
        )
        .unwrap();
        fs::write(
            directory.join("vendor/NOTICE.txt"),
            "Copyright Bob\nAttribution\n",
        )
        .unwrap();
        fs::write(
            directory.join("vendor/license.rs"),
            "additional license text",
        )
        .unwrap();
        let graph = Graph {
            crates: vec![CrateLicense {
                package: Package {
                    name: "fixture".into(),
                    version: "1.0.0".into(),
                    license: Some("MIT".into()),
                    source: Some("registry".into()),
                    manifest_path: directory.join("Cargo.toml"),
                },
            }],
        };
        let text = render(root.path(), graph, &[]).unwrap();
        assert!(text.contains("Copyright Alice\nMIT terms"));
        assert!(text.contains("Copyright Bob\nAttribution"));
        assert!(text.contains("fixture 1.0.0 / vendor/NOTICE.txt"));
        assert!(!text.contains(root.path().to_str().unwrap()));
    }

    #[test]
    fn changed_native_version_requires_review() {
        let native = NativeNotices {
            name: "duckdb".into(),
            version: "1.0.0".into(),
            output: "unused.txt".into(),
        };
        let error = render(Path::new("."), Graph { crates: vec![] }, &[native]).unwrap_err();
        assert!(error.to_string().contains("dependency version changed"));
    }
}
